# Generated by Django 6.0.3 on 2026-04-19 03:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_class', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('role', models.CharField(choices=[('TEACHER', 'Profesor'), ('ADMIN', 'Administrativo'), ('STUDENT', 'Estudiante'), ('IA', 'IA')], max_length=20)),
                ('semester', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_class.department')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_class.program')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('link', models.URLField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_users.profile')),
            ],
        ),
    ]
