# Generated by Django 6.0.3 on 2026-04-19 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
