# Generated by Django 6.0.3 on 2026-04-20 03:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_class', '0002_initial'),
        ('app_users', '0002_alter_socialmedia_link_alter_socialmedia_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name': 'Red social', 'verbose_name_plural': 'Redes sociales'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_class.department', verbose_name='Facultad'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_class.program', verbose_name='Programa'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('TEACHER', 'Profesor'), ('ADMIN', 'Administrativo'), ('STUDENT', 'Estudiante'), ('IA', 'IA')], max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='semester',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='Semestre'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Nombre de la red social'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_users.profile', verbose_name='Perfil asociado'),
        ),
    ]
