# Generated by Django 6.0.3 on 2026-04-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_alter_profile_options_alter_socialmedia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.TextField(default='https://img.freepik.com/vector-premium/icono-usuario-establece-perfil-social-simbolo-vectorial-avatar-persona-cuenta-signo-web_268104-14523.jpg?semt=ais_hybrid&w=740&q=80'),
        ),
    ]
