# Generated by Django 6.0.3 on 2026-05-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('TEACHER', 'Profesor'), ('ADMIN', 'Administrativo'), ('STUDENT', 'Estudiante')], max_length=20, verbose_name='Rol'),
        ),
    ]
