# Generated by Django 6.0.3 on 2026-04-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('CLASS', 'Clase'), ('EXAM', 'Examen'), ('MEETING', 'Reunión'), ('ADVISING', 'Asesoría'), ('OTHER', 'Otro')], default='OTHER', max_length=20),
        ),
    ]
