# Generated by Django 6.0.3 on 2026-04-30 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_calendar', '0002_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='recurrenceRule',
        ),
        migrations.AddField(
            model_name='event',
            name='isRecurrent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='calendar_events', to='app_calendar.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Programado'), ('CANCELLED', 'Cancelado'), ('ONGOING', 'En curso'), ('COMPLETED', 'Completado')], default='SCHEDULED', max_length=20),
        ),
        migrations.CreateModel(
            name='Advising',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_calendar.event')),
                ('state', models.CharField(choices=[('PENDING', 'Pendiente'), ('SCHEDULED', 'Programada'), ('CANCELLED', 'Cancelada')], default='SCHEDULED', max_length=20)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_events', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('app_calendar.event',),
        ),
        migrations.AddField(
            model_name='calendar',
            name='advisings',
            field=models.ManyToManyField(blank=True, related_name='calendar_advisings', to='app_calendar.advising'),
        ),
        migrations.CreateModel(
            name='Event_recurrence',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_calendar.event')),
                ('recurrenceRule', models.CharField(choices=[('DAILY', 'Diaria'), ('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensual'), ('YEARLY', 'Anual')], default='DAILY', max_length=100)),
            ],
            bases=('app_calendar.event',),
        ),
        migrations.AddField(
            model_name='calendar',
            name='event_recurrence',
            field=models.ManyToManyField(blank=True, related_name='calendar_recurrences', to='app_calendar.event_recurrence'),
        ),
    ]
