# Generated by Django 6.0.3 on 2026-04-30 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_calendar', '0003_remove_event_recurrencerule_event_isrecurrent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advising',
            options={'verbose_name': 'Asesoría', 'verbose_name_plural': 'Asesorías'},
        ),
        migrations.AlterModelOptions(
            name='calendar',
            options={'verbose_name': 'Calendario', 'verbose_name_plural': 'Calendarios'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='event_recurrence',
            options={'verbose_name': 'Evento recurrente', 'verbose_name_plural': 'Eventos recurrentes'},
        ),
        migrations.AlterField(
            model_name='advising',
            name='advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_events', to=settings.AUTH_USER_MODEL, verbose_name='Asesor'),
        ),
        migrations.AlterField(
            model_name='advising',
            name='state',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('SCHEDULED', 'Programada'), ('CANCELLED', 'Cancelada')], default='SCHEDULED', max_length=20, verbose_name='Estado de la asesoría'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='advisings',
            field=models.ManyToManyField(blank=True, related_name='calendar_advisings', to='app_calendar.advising', verbose_name='Asesorías'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='event_recurrence',
            field=models.ManyToManyField(blank=True, related_name='calendar_recurrences', to='app_calendar.event_recurrence', verbose_name='Eventos recurrentes'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='calendar_events', to='app_calendar.event', verbose_name='Eventos'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='firstDay',
            field=models.CharField(choices=[('SUNDAY', 'Domingo'), ('MONDAY', 'Lunes'), ('SATURDAY', 'Sábado')], max_length=20, verbose_name='Primer día de la semana'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='timeZone',
            field=models.CharField(max_length=50, verbose_name='Zona horaria'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='event',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='event',
            name='endDateTime',
            field=models.DateTimeField(verbose_name='Fecha y hora de fin'),
        ),
        migrations.AlterField(
            model_name='event',
            name='isRecurrent',
            field=models.BooleanField(default=False, verbose_name='¿Es recurrente?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='event',
            name='startDateTime',
            field=models.DateTimeField(verbose_name='Fecha y hora de inicio'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Programado'), ('CANCELLED', 'Cancelado'), ('ONGOING', 'En curso'), ('COMPLETED', 'Completado')], default='SCHEDULED', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('CLASS', 'Clase'), ('EXAM', 'Examen'), ('MEETING', 'Reunión'), ('ADVISING', 'Asesoría'), ('OTHER', 'Otro')], default='OTHER', max_length=20, verbose_name='Tipo de evento'),
        ),
        migrations.AlterField(
            model_name='event_recurrence',
            name='recurrenceRule',
            field=models.CharField(choices=[('DAILY', 'Diaria'), ('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensual'), ('YEARLY', 'Anual')], default='DAILY', max_length=100, verbose_name='Regla de recurrencia'),
        ),
    ]
