# Generated by Django 6.0.3 on 2026-05-01 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_calendar', '0004_alter_advising_options_alter_calendar_options_and_more'),
        ('app_users', '0004_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advising',
            name='state',
        ),
        migrations.AlterField(
            model_name='advising',
            name='advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_events', to='app_users.profile', verbose_name='Asesor'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_users.profile', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='event',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to='app_users.profile', verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Programado'), ('CANCELLED', 'Cancelado'), ('ONGOING', 'En curso'), ('COMPLETED', 'Completado'), ('PENDING', 'Pendiente')], default='SCHEDULED', max_length=20, verbose_name='Estado'),
        ),
    ]
