# Generated by Django 6.0.3 on 2026-05-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_calendar', '0005_remove_advising_state_alter_advising_advisor_and_more'),
        ('app_users', '0005_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to='app_users.profile', verbose_name='Usuarios invitados'),
        ),
    ]
