# Generated by Django 6.0.3 on 2026-05-07 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_calendar', '0006_event_participants'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
