"""
Django settings for Django project.

Generated by 'django-admin startproject' using Django 6.0.3.
"""
from .utils.logger import *
from .utils.branch_config import *
from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()


title("Configurando settings.py")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
log_debug(f"BASE_DIR configurado en {BASE_DIR}")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q=i=u1!*x!=g4e#pxa%_@vdwz+)c1oc!4iovld9p5lymfhnvx6'
log_warning("Usando SECRET_KEY de desarrollo, no apto para producción")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Django',
    'app_admin',
    'app_class',
    'app_ai',
    'app_calendar',
    'app_chat',
    'app_notifications',
    'app_users',
    'channels',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Django.urls'
log_debug(f"ROOT_URLCONF definido en {ROOT_URLCONF}")

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Django.wsgi.application'
ASGI_APPLICATION = 'Django.asgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# DEBUG = True # cargados en branch config
# ALLOWED_HOSTS "" # cargados en branch config
LANGUAGE_CODE = 'es-co'
TIME_ZONE = 'America/Bogota'
USE_I18N = True
USE_TZ = True
log_debug(f"Idioma: {LANGUAGE_CODE}, Zona horaria: {TIME_ZONE}")

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

LOGIN_URL = '/users/auth/'
LOGIN_REDIRECT_URL = '/home/'
log_debug(f"LOGIN_URL: {LOGIN_URL}, LOGIN_REDIRECT_URL: {LOGIN_REDIRECT_URL}")

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "equiporoblox520@gmail.com"
EMAIL_HOST_PASSWORD = "cypv mhvo imbu cjjy"
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}

# ─────────────────────────────────────────────────────────────
#  MODELO LLM
# ─────────────────────────────────────────────────────────────
 
# Proveedor: "hf" (HuggingFace)
LLM_PROVIDER    = os.getenv("LLM_PROVIDER",    "novita")
LLM_MODEL_ID    = os.getenv("LLM_MODEL_ID",    "meta-llama/Llama-3.1-8B-Instruct")
LLM_MAX_TOKENS  = int(os.getenv("LLM_MAX_TOKENS",  "512"))
LLM_TEMPERATURE = float(os.getenv("LLM_TEMPERATURE", "0.4"))
LLM_TOP_P       = float(os.getenv("LLM_TOP_P",       "0.9"))
 
# ─────────────────────────────────────────────────────────────
#  API KEYS
# ─────────────────────────────────────────────────────────────
 
# HuggingFace (si LLM_PROVIDER = "hf")
HF_TOKEN        = os.getenv("HF_TOKEN", "")
 
 
# Google Maps (para el mapa del campus)
GOOGLE_MAPS_KEY = os.getenv("GOOGLE_MAPS_KEY", "")
 
# ─────────────────────────────────────────────────────────────
#  RAG — Embeddings y búsqueda semántica
# ─────────────────────────────────────────────────────────────
 
AI_EMBEDDING_MODEL = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
AI_DOCS_DIR        = BASE_DIR / "app_ai" / "data" / "documents"
AI_FAISS_DIR       = BASE_DIR / "app_ai" / "data" / "faiss_index"
 
# ─────────────────────────────────────────────────────────────
#  DIRECTORIOS DE DATOS (se crean si no existen)
# ─────────────────────────────────────────────────────────────
 
for _dir in [AI_DOCS_DIR, AI_FAISS_DIR, BASE_DIR / "app_ai" / "data" / "logs"]:
    _dir.mkdir(parents=True, exist_ok=True)
 
